;TEXT.SAM - ERROR MESSAGES, KEYWORDS, MSGS, TABLES, CHARSET ETC

;REPORTS GENERATED BY E.G. RST 08H: DB 0 FOR OK
;UTILITY MESSAGES (START AT 0)

;UMVAL IS LOADED INTO UMSGS SYS VAR AT INIT.
UMVAL:

  DM "   MILES GORDON TECHNOLOGY PLC  "
  DM "     "
  DB 127
  DM " 1990  SAM Cou"
  DB "p"+&80  ;0

  DM "scroll"
  DB "?"+&80  ;1

  DB " "+&80  ;2 NOT USED

  DM "St"
  DB CAR
  DM "t tape and then press a ke"
  DB "y"+&80  ;3

  DM "Basic:"
  DB " "+&80  ;4

  DM "Nu"
  DB CME
  DM "ric"
  DB ARRAY+&80  ;5

  DB STRING,ARRAY+&80  ;6

  DM "Co"
  DB CDE,":"," "+&80  ;7

  DB "S",CREEN,":"," "+&80  ;8

;ERRMVAL IS LOADED INTO ERRMSGS SYS VAR AT INIT.
ERRMVAL:

  DB "O","K"+&80  ;0

  DM "Out"
  DB SOFS,CME
  DM "mor"
  DB "y"+&80  ;1

  DB SNOTS
  DM "foun"
  DB "d"+&80  ;2

  DM "DATA has all been rea"
  DB "d"+&80  ;3

  DM "Subscript wron"
  DB "g"+&80  ;4

  DB CNXT,WITHOUT
  DM "FO"
  DB "R"+&80  ;5

  DM "FOR"
  DB WITHOUT,CNXT+&80  ;6

  DM "FN"
  DB WITHOUT
  DM "DEF F"
  DB "N"+&80  ;7

  DM "RETURN"
  DB WITHOUT
  DM "GOSU"
  DB "B"+&80  ;8

  DB MISSING,CLOOP+&80  ;9

  DB CLOOP,WITHOUT,"D","O"+&80  ;10

  DB NO
  DM "POP dat"
  DB "a"+&80  ;11

  DB MISSING
  DM "DEF"
  DB CPROC+&80  ;12

  DB NO
  DM "END"
  DB CPROC+&80  ;13

  DB BREAK
  DM "- CONTINUE "
  DB CTO
  DM " repea"
  DB "t"+&80  ;14

  DB BREAK,CIN,CTO
  DM " progra"
  DB "m"+&80  ;15

  DB CSTOP,"s",TATEMENT+&80  ;16

  DB CSTOP,CIN
  DM " INPU"
  DB "T"+&80  ;17

  DB INVALID,FILE,SNAME+&80  ;18

  DM "Load"
  DB CIN,"g",ERROR+&80  ;19

  DB INVALID,CDE
  DM "vic"
  DB "e"+&80  ;20

  DB INVALID,"s",TREAM
  DM " n"
  DB UMBER+&80  ;21

  DM "End"
  DB SOFS,FILE+&80  ;22

  DB INVALID,CLOUR+&80  ;23

  DB INVALID,PALET,CLOUR+&80  ;24

  DB TOOMANY,PALET
  DM "change"
  DB "s"+&80  ;25

  DB "P",CAR,"a",CME
  DM "ter"
  DB ERROR+&80  ;26

  DB INVALID,CAR
  DM "gu"
  DB CME,"n","t"+&80  ;27

  DB "N",UMBER,TOO,"l",CAR,"g","e"+&80  ;28

  DM "Not un"
  DB CDE
  DM "rs"
  DB CTO,"o","d"+&80  ;29

  DM "Integer out"
  DB SOFS
  DM "rang"
  DB "e"+&80  ;30

  DB "S",TATEMENT
  DM " doesn't exis"
  DB "t"+&80  ;31

  DM "Off s"
  DB CREEN+&80  ;32

  DB NO
  DM "room for l"
  DB CIN,"e"+&80  ;33

  DB INVALID,"s",CREEN
  DM " mod"
  DB "e"+&80  ;34

  DB INVALID
  DM "BLITZ cod"
  DB "e"+&80  ;35

  DB "S",CTO
  DM "red "
  DB CAR
  DM "ea"
  DB TOO
  DM "bi"
  DB "g"+&80  ;36

  DB INVALID
  DM "PUT bloc"
  DB "k"+&80  ;37

  DM "PUT mask mismatc"
  DB "h"+&80  ;38

  DB MISSING
  DM "END I"
  DB "F"+&80  ;39

  DB INVALID,"v",CAR
  DM "iable"
  DB SNAME+&80  ;40

  DM "BASIC stack ful"
  DB "l"+&80  ;41

  DB STRING,TOO,LONG+&80  ;42

  DB INVALID,"s",CREEN
  DM " n"
  DB UMBER+&80  ;43

  DB "S",CREEN,ISALREDOP+&80  ;44

  DB "S",TREAM,ISALREDOP+&80  ;45

  DM "Current s"
  DB CREEN+&80  ;46  WAS INVALID CHANNEL

  DB "S",TREAM
  DM " is"
  DB SNOTS
  DM "ope"
  DB "n"+&80  ;47

  DB INVALID
  DM "CLEAR addres"
  DB "s"+&80  ;48

  DB INVALID,NOTE+&80  ;49

  DB NOTE,TOO,LONG+&80  ;50

  DM "FPC"
  DB ERROR+&80  ;51

  DB TOOMANY,CDE,"f",CIN
  DM "ition"
  DB "s"+&80  ;52

  DM "No DO"
  DB "S"+&80  ;53

  DB INVALID
  DM "WINDO"
  DB "W"+&80  ;54

  DB MISSING
  DM "dis"
  DB "k"+&80  ;55

;SAVES OVER 200 BYTES.

COMPLIST:  DM "Invalid"
           DB " "+&80            ;14 uses

INVALID:   EQU 0

           DM " without"
           DB " "+&80           ;5 uses

WITHOUT:   EQU 1

           DM "Missing"
           DB " "+&80            ;5 uses

MISSING:   EQU 2

           DM " too"
           DB " "+&80               ;3 uses

TOO:       EQU 3

           DM " is already ope"
           DB "n"+&80    ;2 uses

ISALREDOP: EQU 4

           DM "palette"
           DB " "+&80            ;2 uses

PALET:     EQU 5

           DM " of"
           DB " "+&80                ;3 uses

SOFS:      EQU 6

           DM " erro"
           DB "r"+&80              ;4 uses

ERROR:     EQU 7

           DM "trea"
           DB "m"+&80               ;3 uses

TREAM:     EQU 8

           DM "umbe"
           DB "r"+&80               ;3 uses

UMBER:     EQU 9

           DM "NEX"
           DB "T"+&80                ;2 uses

CNXT:      EQU 10

           DM "No"
           DB " "+&80                 ;3 uses

NO:        EQU 11

           DM "BREAK"
           DB " "+&80              ;2 uses

BREAK:     EQU 12

           DM "cree"
           DB "n"+&80               ;6 USES

CREEN:     EQU 13

           DM " array:"
           DB " "+&80            ;2 USES

ARRAY:     EQU 14

           DM "Not"
           DB "e"+&80                ;2 USES

NOTE:      EQU 15

           DM "lon"
           DB "g"+&80                ;2 USES

LONG:      EQU 16

           DM " not"
           DB " "+&80               ;2 USES

SNOTS:     EQU 17

           DM " nam"
           DB "e"+&80               ;2 USES

SNAME:     EQU 18

           DM "Strin"
           DB "g"+&80          ;2 USES

STRING:    EQU 19

           DM "Too many"
           DB " "+&80       ;2 USES

TOOMANY:   EQU 20

           DM "tatemen"
           DB "t"+&80         ;2 USES

TATEMENT:  EQU 21

           DM "STOP"
           DB " "+&80           ;2 USES

CSTOP:     EQU 22

           DM "fil"
           DB "e"+&80            ;2 USES

FILE:      EQU 23

           DM "colou"
           DB "r"+&80          ;2 USES

CLOUR:     EQU 24

           DB "i","n"+&80              ;5 USES

CIN:       EQU 25

           DM " PRO"
           DB "C"+&80           ;2 USES

CPROC:     EQU 26

           DM "LOO"
           DB "P"+&80            ;2 USES

CLOOP:     EQU 27

           DB "t","o"+&80              ;4 USES

CTO:       EQU 28

           DB "d","e"+&80              ;4 USES

CDE:       EQU 29

           DB "m","e"+&80              ;2 USES

CME:       EQU 30

           DB "a","r"+&80              ;6 USES

CAR:       EQU 31

;TOKENS.SAM - SAM TOKEN TABLE.
;FUNCTIONS RANGE 21-&69, PRECEDED BY FF
;ASCII RANGE 20-7F
;BLOCK GRAPHICS/EXTENDED CHARS  80-8F
;EXTENDED CHARS 90-A8
;(&80-A8H ACT AS UDGS - PROGRAMMED AS BLOCK GRAPHICS, FOLLOWED BY EXTENDED CHARS
;ON POWER-UP. UDGS SYS VAR PTS TO USR "A". TAKES 328 BYTES OF RAM. OVERLAP WITH
;COMMAND TOKENS USES CONTEXT TO AVOID PROBLEMS - PRINT CHR$ 160 GIVES UDG, LIST
;COMMAND GIVES KEYWORD. QUOTES FORCES UDGS.
;ALLOW 80-95 IN PROC NAMES SO A FACE SYMBOL CAN BE A COMMAND?
;USE "." FOR EXTERNAL COMMAND

;QUALIFIERS  96-9F
;COMMANDS RANGE A0-FE

;FUNCTIONS HAVE &0FF PREFIX

;"IMMEDIATE" FUNCTIONS

KEYWTAB:      DB &A0

IMFNTL:       DM "P"            ;&3B
              DB "I"+&80

              DM "RN"           ;
              DB "D"+&80

              DM "POIN"         ;
              DB "T"+&80

              DM "FRE"          ;
              DB "E"+&80

              DM "LENGT"        ;
              DB "H"+&80

              DM "ITE"          ;
              DB "M"+&80

              DM "ATT"          ;
              DB "R"+&80

              DM "F"            ;
              DB "N"+&80

              DM "BI"           ;
              DB "N"+&80

              DM "XMOUS"        ;
              DB "E"+&80

              DM "YMOUS"        ;
              DB "E"+&80

              DM "XPE"          ;
              DB "N"+&80

              DM "YPE"          ;
              DB "N"+&80

              DM "RAMTO"        ;
              DB "P"+&80

              DB "-"+&80        ; UNUSED INARRAY

              DM "INST"         ;&4A
              DB "R"+&80

              DM "INKEY"        ;&4B
              DB "$"+&80


              DM "SCREEN"       ;
              DB "$"+&80

              DM "MEM"          ;
              DB "$"+&80

              DB "-"+&80        ; UNUSED CHAR$

              DM "PATH"         ;
              DB "$"+&80

              DM "STRING"       ;
              DB "$"+&80

              DB "-"+&80        ; UNUSED USING$
              DB "-"+&80        ;&52 UNUSED SHIFT$

;FPC FUNCTIONS

FPCFNTL:      DM "SI"           ;&53
              DB "N"+&80

              DM "CO"           ;
              DB "S"+&80

              DM "TA"           ;
              DB "N"+&80

              DM "AS"           ;
              DB "N"+&80

              DM "AC"           ;
              DB "S"+&80

              DM "AT"           ;
              DB "N"+&80

              DM "L"            ;
              DB "N"+&80

              DM "EX"           ;
              DB "P"+&80

              DM "AB"           ;
              DB "S"+&80

              DM "SG"           ;
              DB "N"+&80

              DM "SQ"           ;
              DB "R"+&80

              DM "IN"           ;
              DB "T"+&80

              DM "US"           ;
              DB "R"+&80

              DM "I"            ;
              DB "N"+&80

              DM "PEE"          ;
              DB "K"+&80

              DM "DPEE"         ;
              DB "K"+&80

              DM "DVA"          ;
              DB "R"+&80

              DM "SVA"          ;
              DB "R"+&80

              DM "BUTTO"        ;
              DB "N"+&80

              DM "EO"           ;
              DB "F"+&80

              DM "PT"           ;   DISC USE?
              DB "R"+&80

              DB "-"+&80

              DM "UD"           ;
              DB "G"+&80

              DB "-"+&80

              DM "LE"           ;
              DB "N"+&80

              DM "COD"          ;
              DB "E"+&80

              DM "VAL"          ;
              DB "$"+&80

              DM "VA"           ;
              DB "L"+&80

              DM "TRUNC"        ;
              DB "$"+&80

              DM "CHR"          ;
              DB "$"+&80

              DM "STR"          ;
              DB "$"+&80

              DM "BIN"          ;
              DB "$"+&80

              DM "HEX"          ;
              DB "$"+&80

              DM "USR"          ;
              DB "$"+&80

              DB "-"+&80        ; CORRESPONDS TO INKEY$ FPC CODE

              DM "NO"           ;
              DB "T"+&80

              DB "-"+&80        ;
              DB "-"+&80        ;
              DB "-"+&80        ;&79

;BINARY OPERATORS

BINFNTL:      DM "MO"           ;&7A
              DB "D"+&80

              DM "DI"           ;
              DB "V"+&80

              DM "BO"           ;
              DB "R"+&80

              DB "-"+&80

              DM "BAN"          ;
              DB "D"+&80

              DM "O"            ;
              DB "R"+&80

              DM "AN"           ;
              DB "D"+&80

              DM "<"            ;
              DB ">"+&80

              DM "<"            ;
              DB "="+&80

              DM ">"            ;&83
              DB "="+&80



;QUALIFIERS - RANGE &85-&8F

KWDS85:       DM "USIN"             ;&85
              DB "G"+&80

              DM "WRIT"             ;86
              DB "E"+&80

              DM "A"                ;87
              DB "T"+&80

              DM "TA"               ;88
              DB "B"+&80

              DM "OF"               ;89
              DB "F"+&80

              DM "WHIL"             ;8A
              DB "E"+&80

              DM "UNTI"             ;8B
              DB "L"+&80

              DM "LIN"              ;8C
              DB "E"+&80

              DM "THE"              ;8D
              DB "N"+&80

              DM "T"                ;8E
              DB "O"+&80

              DM "STE"              ;8F
              DB "P"+&80

;COMMANDS.  RANGE &90-FEH

              DM "DI"               ;90
              DB "R"+&80

              DM "FORMA"            ;91
              DB "T"+&80

              DM "ERAS"             ;92
              DB "E"+&80

              DM "MOV"              ;93
              DB "E"+&80

              DM "SAV"              ;94
              DB "E"+&80

              DM "LOA"              ;95
              DB "D"+&80

              DM "MERG"             ;96
              DB "E"+&80

              DM "VERIF"            ;97
              DB "Y"+&80

              DM "OPE"              ;98
              DB "N"+&80

              DM "CLOS"             ;99
              DB "E"+&80


              DM "CIRCL"            ;9A
              DB "E"+&80

              DM "PLO"              ;9B
              DB "T"+&80

              DM "LE"               ;9C
              DB "T"+&80

              DM "BLIT"             ;9D
              DB "Z"+&80

              DM "BORDE"            ;9E
              DB "R"+&80

              DM "CL"               ;9F
              DB "S"+&80

KWDSA0:       DM "PALETT"           ;A0
              DB "E"+&80

              DM "PE"               ;A1
              DB "N"+&80

              DM "PAPE"             ;A2
              DB "R"+&80

              DM "FLAS"             ;A3
              DB "H"+&80

              DM "BRIGH"            ;A4
              DB "T"+&80

              DM "INVERS"           ;A5
              DB "E"+&80

              DM "OVE"              ;A6
              DB "R"+&80


              DM "FATPI"            ;A7  0=THIN, 1=FAT
              DB "X"+&80

              DM "CSIZ"             ;A8
              DB "E"+&80

              DM "BLOCK"            ;A9
              DB "S"+&80

              DM "MOD"              ;AA
              DB "E"+&80

              DM "GRA"              ;AB
              DB "B"+&80

              DM "PU"               ;AC
              DB "T"+&80


              DM "BEE"              ;AD
              DB "P"+&80

              DM "SOUN"             ;AE
              DB "D"+&80


              DM "NE"               ;AF
              DB "W"+&80

              DM "RU"               ;B0
              DB "N"+&80

              DM "STO"              ;B1
              DB "P"+&80

              DM "CONTINU"          ;B2
              DB "E"+&80

              DM "CLEA"             ;B3
              DB "R"+&80

              DM "GO T"             ;B4
              DB "O"+&80

              DM "GO SU"            ;B5
              DB "B"+&80

              DM "RETUR"            ;B6
              DB "N"+&80

              DM "RE"               ;B7
              DB "M"+&80


              DM "REA"              ;B8
              DB "D"+&80

              DM "DAT"              ;B9
              DB "A"+&80

              DM "RESTOR"           ;BA
              DB "E"+&80


              DM "PRIN"             ;BB
              DB "T"+&80

              DM "LPRIN"            ;BC
              DB "T"+&80

              DM "LIS"              ;BD
              DB "T"+&80

              DM "LLIS"             ;BE
              DB "T"+&80

              DM "DUM"              ;BF
              DB "P"+&80

KWDSC0:       DM "FO"               ;C0
              DB "R"+&80

              DM "NEX"              ;C1
              DB "T"+&80

              DM "PAUS"             ;C2
              DB "E"+&80

              DM "DRA"              ;C3
              DB "W"+&80

              DM "DEFAUL"           ;C4
              DB "T"+&80

              DM "DI"               ;C5
              DB "M"+&80

              DM "INPU"             ;C6
              DB "T"+&80

              DM "RANDOMIZ"         ;C7
              DB "E"+&80

              DM "DEF F"            ;C8
              DB "N"+&80

              DM "DEF KEYCOD"       ;C9
              DB "E"+&80

              DM "DEF PRO"          ;CA
              DB "C"+&80

              DM "END PRO"          ;CB
              DB "C"+&80

              DM "RENU"             ;CC
              DB "M"+&80

              DM "DELET"            ;CD
              DB "E"+&80

              DM "RE"               ;CE
              DB "F"+&80

              DM "COP"              ;CF
              DB "Y"+&80

              DB "-"+&80            ;D0

              DM "KEYI"             ;D1
              DB "N"+&80

              DM "LOCA"             ;D2
              DB "L"+&80

              DM "LOOP I"           ;D3
              DB "F"+&80

              DM "D"                ;D4
              DB "O"+&80

              DM "LOO"              ;D5
              DB "P"+&80

              DM "EXIT I"           ;D6
              DB "F"+&80

              DM "I"                ;D7
              DB "F"+&80

              DM "I"                ;D8
              DB "F"+&80

              DM "ELS"              ;D9
              DB "E"+&80

              DM "ELS"              ;DA
              DB "E"+&80

              DM "END I"            ;DB
              DB "F"+&80

              DM "KE"               ;DC
              DB "Y"+&80

              DM "ON ERRO"          ;DD
              DB "R"+&80

              DM "O"                ;DE
              DB "N"+&80

              DM "GE"               ;DF
              DB "T"+&80

KWDSE0:       DM "OU"               ;E0
              DB "T"+&80

              DM "POK"              ;E1
              DB "E"+&80

              DM "DPOK"             ;E2
              DB "E"+&80

              DM "RENAM"            ;E3
              DB "E"+&80

              DM "CAL"              ;E4
              DB "L"+&80

              DM "ROL"              ;E5
              DB "L"+&80

              DM "SCROL"            ;E6
              DB "L"+&80

              DM "SCREE"            ;E7
              DB "N"+&80

              DM "DISPLA"           ;E8
              DB "Y"+&80

BTWD:         DM "BOO"              ;E9 USED BY BOOT TO CHECK FILE NAME
              DB "T"+&80

              DM "LABE"             ;EA
              DB "L"+&80

              DM "FIL"              ;EB
              DB "L"+&80

              DM "WINDO"            ;EC
              DB "W"+&80

              DM "AUT"              ;ED
              DB "O"+&80

              DM "PO"               ;EE
              DB "P"+&80

              DM "RECOR"            ;EF
              DB "D"+&80

              DM "DEVIC"            ;F0
              DB "E"+&80

              DM "PROTEC"           ;F1
              DB "T"+&80

              DM "HID"              ;F2
              DB "E"+&80

              DM "ZA"               ;F3
              DB "P"+&80

              DM "PO"               ;F4
              DB "W"+&80

              DM "BOO"              ;F5
              DB "M"+&80

              DM "ZOO"              ;F6
              DB "M"+&80

              DB "-"+&80            ;F7
              DB "-"+&80            ;F8
              DB "-"+&80            ;F9
              DB "-"+&80            ;FA
              DB "-"+&80            ;FB
              DB "-"+&80            ;FC
              DB "-"+&80            ;FD
              DB "-"+&80            ;FE

              DM "IN"               ;FF (FUNCTION PREFIX) AND TEMP "INK" TOKEN
              DB "K"+&80



;DEF KEY INIT TABLE

DKSRC:     DB 192,1,0,&BD                            ;F0 LIST
           DB 193,2,0,&CC,":"                        ;F1 RENUM :
           DB 194,2,0,&BB,":"                        ;F2 PRINT :
           DB 195,2,0,&AA,":"                        ;F3 MODE :
           DB 196,1,0,&B0                            ;F4 RUN
           DB 197,1,0,&B2                            ;F5 CONTINUE
           DB 198,2,0,&9F,"#"                        ;F6 CLS #
           DB 199,3,0,LOADTOK,&22,&22                ;F7 LOAD ""
           DB 200,5,0,LOADTOK,&22,&22,&FF,CODETOK    ;F8 LOAD "" CODE
           DB 201,1,0,&E9                            ;F9 BOOT

           DB 252,2,0,6,":"                          ;TAB
           DB 253,3,0,20,1,":"                       ;INVERSE 1 CC
           DB 254,3,0,20,0,":"                       ;INVERSE 0 CC
DKEN:      DB &FF

;INIT TABLE - 18 BYTES

CHIT:      DB ">"        ;CURRENT LINE CURSOR
           DB 128,129    ;CURSOR CHARACTERS - LOWER CASE/UPPER CASE
           DB "1","0"    ;DIGIT CHARS FOR "BIN$"
           DB "#"        ;INSTR WILD CARD CHAR
           DB "T",TSPEED ;DEVICE T, TAPE SPEED
           DB 17         ;COLOUR FLASH SPEED
           DW LINICOLS   ;LINIPTR
           DB &FF,0,0    ;XCMDP SHOWS "NO EXTERNAL CMDS"

           DB 79         ;PRINTER RHS
           DB 10         ;AFTER CR CHARACTER
           DB &E9        ;PRINTER CONTROL PORT (E8=DATA)
           DB 1          ;PRINTER STROBE BYTE

MAIT:      DW BSTACK     ;BASSTK
           DW HPEND      ;HEAPEND
           DW HPEND      ;HPST  START WITH EMPTY HEAP
           DW FPSB       ;FPSBOT
           DW DKBU       ;DEF KEY BUFFER START
           DW DKBU+128   ;LIMIT OF DEF KEY BUFFER GROWTH
           DW ENDOUTP    ;"PRINTABLE CHARS" O/P ROUTINE
           DW ERRMVAL    ;ERROR MESSAGES
           DW UMVAL      ;"UTILITY" MESSAGES
           DW KTAB       ;KEYBOARD TABLE
           DW CMDADT     ;START OF CMD ADDR TABLE
                         ;FIRST 4 BYTES IN CHANTAB ALSO USED!

CHANTAB:   DW PRMAIN
           DW KYIP
           DB "K"

           DW PRMAIN
           DW KYIP
           DB "S"

           DW ADDCHAR
           DW IDERR
           DB "R"

           DW PRMAIN
           DW IDERR
           DB "P"

           DW S16OP
           DW IDERR
           DB "$"

           DW SENDA
           DW IDERR
           DB "B"

           DB &0D            ;KEEPS READ CMD HAPPY ON FIRST LINE

;KEY MAP FOR 70 KEYS (3 NOT READ THIS WAY) IN UNSHIFTED, CAPS SHIFTED AND SYMB.
;SHIFTED STATES. EACH ROW CORRESPONDS TO A BIT ON THE PORT (BIT 7 AT TOP) AND
;EACH COLUMN TO A PORT MSB. CAPS SHIFT (BIT 0,PORT FE) SCANNED SEPARATELY, AS
;IS SYM SHIFT (BIT 1,PORT 7F) AND CONTROL (BIT 0,PORT FF)

;PORT MSB:     FF  7F  BF  DF  EF  F7  FB  FD  FE
;BIT MAP BYTE  8   7   6   5   4   3   2   1   0

;254 DEFINED AS INVERSE CC,0
;253 DEFINED AS INVERSE CC,1
;252 DEFINED AS CHR$ 6

KSRC:      DB     253,&07,&C0, 12,&06,&C9,198,195  ;BIT 7
           DB "X",".",":", 34,"+",252,200,197,194  ;    6
           DB "X",",",";","=","-"," ",199,196,193  ;    5

           DB &09,"b","h","y","6","5","t","g","v"  ;    4
           DB &08,"n","j","u","7","4","r","f","c"  ;    3
           DB &0A,"m","k","i","8","3","e","d","x"  ;    2
           DB &0B,"X","l","o","9","2","w","s","z"  ;    1
           DB "X"," ",&0D,"p","0","1","q","a"      ;    0

;CAPS SHIFTED

           DB     "\",&07,202,&0E,&06,211,208,205
           DB "X",".",":",127,"*",252,210,207,204
           DB "X",",",";","_","/"," ",209,206,203

           DB &09,"B","H","Y","&","%","T","G","V"
           DB &08,"N","J","U","'","$","R","F","C"
           DB &0A,"M","K","I","(","#","E","D","X"
           DB &0B,"X","L","O",")","@","W","S","Z"
           DB "X"," ",&0D,"P",126,"!","Q","A"

;SYMBOL SHIFTED

           DB     254,&0F,"0",&0E,&06,"9","6","3"
           DB "X",">","*",&CF,"*",252,"8","5","2"
           DB "X","<","+","_","/"," ","7","4","1"

           DB &09,&9E,&5E,157,134,133,"]","}",VERIFYTOK
           DB &08,164,"-",129,135,132,"[","{",168
           DB &0A,165,"+",&A5,128,131,130,&9C,"?"
           DB &0B,"X",&60,148,124,130,">",SAVETOK,"?"
           DB "X"," ",&0D,187,126,129,"<",&B1


;CONTROL KEY TABLE - DISP/VALUE

CKTAB:     DB 19,3           ;BRIGHT CC
           DB 137,1          ;GRAPHICS
           DB 138,8
           DB 136,1
           DB 139,7
           DB 16,1           ;PEN CC
           DB 143,1
           DB 140,9
           DB 141,7
           DB 17,2           ;PAPER CC
           DB 142,0


;INITIAL PALETTE COLOURS - MS GRB BITS, BRIGHT BIT, LS GRB BITS
;                GRBbGRB

INITCOLS:    DB %0000000     ;BLACK
             DB %0010000     ;BLUE
             DB %0100000     ;RED
             DB %0110000     ;MAGENTA
             DB %1000000     ;GREEN
             DB %1010000     ;CYAN
             DB %1100000     ;YELLOW
             DB %1111000     ;WHITE

             DB %0000000     ;BRIGHT BLACK=BLACK
             DB %0010001     ;BLUE
             DB %0100010     ;RED
             DB %0110011     ;MAGENTA
             DB %1000100     ;GREEN
             DB %1010101     ;CYAN
             DB %1100110     ;YELLOW
             DB %1111111     ;WHITE

            ;COLOURS FOR 4-COLOUR MODE

             DB %0000000     ;BLACK
             DB %0010001     ;BLUE
             DB %0100010     ;RED
             DB %1111111     ;WHITE

;COMMAND ADDRESS TABLE.  RANGE 90H-FEH

CMDADT:    DW NONSENSE      ;DIR      90 ** ALTERED
           DW NONSENSE      ;FORMAT   91
           DW NONSENSE      ;ERASE    92
           DW NONSENSE      ;MOVE     93
           DW SLMVC         ;SAVE     94
           DW SLMVC         ;LOAD     95
           DW SLMVC         ;MERGE    96
           DW SLMVC         ;VERIFY   97
           DW OPSCRN        ;OPEN     98
           DW CLSCRN        ;CLOSE    99
           DW CIRCLE        ;CIRCLE   9A
           DW PLOT          ;PLOT     9B
           DW LET           ;LET      9C
           DW BLITZ         ;BLITZ    9D
           DW BORDER        ;BORDER   9E
           DW CLS           ;CLS      9F

           DW COLOUR        ;PALETTE  A0
           DW PERMS         ;INK      A1
           DW PERMS         ;PAPER    A2
           DW PERMS         ;FLASH    A3
           DW PERMS         ;BRIGHT   A4
           DW PERMS         ;INVERSE  A5
           DW PERMS         ;OVER     A6
           DW FATPIX        ;FATPIX   A7  PIXEL WIDTH
           DW WIDTH         ;CSIZE    A8
           DW BGRAPHICS     ;BLOCKS   A9  BLOCK GRAPHICS/UDGS
           DW MODECMD       ;MODE     AA
           DW GRAB          ;GRAB     AB
           DW PUT           ;PUT      AC
           DW BEEP          ;BEEP     AD
           DW SOUND         ;SOUND    AE
           DW NEW           ;NEW      AF

           DW RUN           ;RUN      B0
           DW STOP          ;STOP     B1
           DW CONTINUE      ;CONTINUE B2
           DW CLEAR         ;CLEAR    B3
           DW GOTO          ;GO TO    B4
           DW GOSUB         ;GO SUB   B5
           DW RETURN        ;RETURN   B6
           DW REMARK        ;REM      B7
           DW READ          ;READ     B8
           DW DATA          ;DATA     B9
           DW RESTORE       ;RESTORE  BA
           DW PRINT         ;PRINT    BB
           DW LPRINT        ;LPRINT   BC
           DW LIST          ;LIST     BD
           DW LLIST         ;LLIST    BE
           DW COPY          ;DUMP     BF

           DW FOR           ;FOR         C0
           DW NEXT          ;NEXT        C1
           DW PAUSE         ;PAUSE       C2
           DW DRAW          ;DRAW        C3
           DW DEFAULT       ;DEFAULT     C4
           DW DIM           ;DIM         C5
           DW INPUT         ;INPUT       C6
           DW RANDOMIZE     ;RAND        C7
           DW DEFFN         ;DEF FN      C8
           DW DEFKEY        ;DEF KEYCODE C9
           DW DEFPROC       ;DEF PROC    CA
           DW ENDPROC       ;END PROC    CB
           DW RENUM         ;RENUM       CC
           DW DELETE        ;DELETE      CD
           DW NONSENSE      ;REF         CE
           DW NONSENSE      ;COPY        CF

           DW NONSENSE      ;DRIVER   D0
           DW KEYIN         ;KEYIN    D1
           DW LOCAL         ;LOCAL    D2
           DW LOOPIF        ;LOOP IF  D3
           DW DO            ;DO       D4
           DW LOOP          ;LOOP     D5
           DW EXITIF        ;EXIT IF  D6
           DW LIF           ;LONG IF  D7
           DW SIF           ;SHORT IF D8
           DW LELSE         ;LELSE    D9
           DW ELSE          ;ELSE     DA
           DW ENDIF         ;END IF   DB
           DW KEY           ;KEY      DC
           DW ONERROR       ;ON ERROR DD
           DW ON            ;ON       DE
           DW GET           ;GET      DF

           DW OUT           ;OUT      E0
           DW POKE          ;POKE     E1
           DW DPOKE         ;DPOKE    E2
           DW NONSENSE      ;RENAME   E3
           DW CALLER        ;CALL     E4
           DW ROLL          ;ROLL     E5
           DW SCROLL        ;SCROLL   E6
           DW SCREEN        ;SCREEN   E7
           DW DISPLAY       ;DISPLAY  E8
           DW BOOT          ;BOOT     E9
           DW LABEL         ;LABEL    EA
           DW FILL          ;FILL     EB
           DW WINDOW        ;WINDOW   EC
           DW AUTO          ;AUTO     ED
           DW POP           ;POP      EE
           DW RECORD        ;RECORD   EF

           DW SLDEVICE      ;DEVICE   F0
           DW NONSENSE      ;PROTECT  F1
           DW NONSENSE      ;HIDE     F2
           DW ZAP           ;ZAP      F3
           DW POW           ;POW      F4
           DW BOOM          ;BOOM     F5
           DW ZOOM          ;ZOOM     F6
         ;  DW NONSENSE      ;         F7
          ; DW NONSENSE      ;         F8
          ; DW NONSENSE      ;         F9
          ; DW NONSENSE      ;         FA
          ; DW NONSENSE      ;         FB
          ; DW NONSENSE      ;         FC
          ; DW NONSENSE      ;         FD
          ; DW NONSENSE      ;         FE
          ; DW NONSENSE      ;         FF (FUNCTION PREFIX)


;TABLE FOR CHARS THAT USE ALL 8 SCANS; VALUE TO USE FOR SCAN 8, DISP TO NEXT
;SUCH CHAR, ZERO ENDS TABLE

U8TAB:     DB &08,&78        ;","
           DB &08,&80        ;";"
           DB &00,&A0        ;DUMMY
           DB &FF,&40        ;"_"
           DB &1C,&18        ;"g"
           DB &10,&30        ;"j"
           DB &20,&08        ;"p"
           DB &02,&40        ;"q"
           DB &1C            ;"y"

VVAR2:     DB &00,&5A        ;U8TAB TERMINATOR/SVAR BASE ADDR

;USED BY PRINT NUMBER

SUBTAB:    DW -10000
           DW -1000
           DW -100
           DW -10
;          DB  0  CHARSRC 1ST BYTE IS TERMINATOR!

;CHARSET BY SIMON N. GOODWIN
;CHARACTERS USE CENTRE 6 PIXELS, CAN BE UP TO 8 PIXELS HIGH
;COMPRESSED FORM USES 7 5-BIT SLICES PER CHAR, TAKES 600 BYTES VS 1096

CHARSRC:

    DB &00,&00,&00,&00,&04
    DB &21,&08,&40,&11,&4A
    DB &00,&00,&00,&29,&5F
    DB &57,&D4,&A7,&52,&8E
    DB &29,&5D,&9C,&88,&88
    DB &9C,&D1,&4A,&22,&B2
    DB &69,&84,&40,&00,&00
    DB &08,&88,&42,&08,&30
    DB &41,&08,&44,&40,&95
    DB &77,&DD,&52,&00,&84
    DB &F9,&08,&00,&00,&00
    DB &31,&84,&00,&03,&E0
    DB &00,&00,&00,&00,&06
    DB &30,&42,&22,&22,&10
    DB &74,&67,&5C,&C5,&C4
    DB &61,&08,&42,&39,&D1
    DB &08,&88,&8F,&BA,&21
    DB &30,&62,&E1,&19,&52
    DB &F8,&85,&F8,&78,&21
    DB &8B,&8C,&88,&7A,&31
    DB &77,&C2,&22,&22,&10
    DB &74,&62,&E8,&C5,&CE
    DB &8C,&5E,&11,&30,&00
    DB &31,&80,&63,&00,&06
    DB &30,&0C,&20,&88,&88
    DB &20,&82,&00,&7C,&1F
    DB &00,&20,&82,&08,&88
    DB &83,&A2,&11,&10,&04
    DB &74,&67,&5B,&C1,&CE
    DB &8C,&7F,&18,&C7,&D1
    DB &8F,&A3,&1F,&3A,&30
    DB &84,&22,&EF,&46,&31
    DB &8C,&7D,&F8,&43,&D0
    DB &87,&FF,&08,&7A,&10
    DB &83,&A3,&08,&4E,&2E
    DB &8C,&63,&F8,&C6,&2E
    DB &21,&08,&42,&38,&21
    DB &08,&43,&17,&46,&54
    DB &C5,&25,&18,&42,&10
    DB &84,&3F,&1D,&D6,&31
    DB &8C,&63,&1C,&D6,&71
    DB &8B,&A3,&18,&C6,&2E
    DB &F4,&63,&E8,&42,&0E
    DB &8C,&63,&59,&37,&D1
    DB &8F,&A9,&28,&BA,&30
    DB &70,&62,&EF,&90,&84
    DB &21,&09,&18,&C6,&31
    DB &8B,&A3,&18,&C6,&2A
    DB &24,&63,&18,&D6,&AA
    DB &8C,&54,&45,&46,&31
    DB &8A,&88,&42,&13,&E1
    DB &11,&11,&0F,&9C,&84
    DB &21,&08,&78,&41,&04
    DB &10,&43,&C2,&10,&84
    DB &27,&08,&EA,&90,&84
    DB &20,&00,&00,&00,&00
    DB &32,&51,&C4,&23,&E0
    DB &03,&82,&F8,&BE,&10
    DB &F4,&63,&1F,&00,&0F
    DB &84,&20,&F0,&85,&F1
    DB &8C,&5E,&00,&3A,&3F
    DB &83,&CC,&94,&79,&08
    DB &40,&00,&F8,&C5,&E1
    DB &84,&3D,&18,&C6,&24
    DB &01,&08,&42,&08,&80
    DB &21,&08,&42,&42,&11
    DB &97,&25,&12,&10,&84
    DB &21,&0C,&00,&6A,&B5
    DB &AD,&40,&0F,&46,&31
    DB &88,&00,&E8,&C6,&2E
    DB &00,&3D,&18,&FA,&00
    DB &03,&E3,&17,&84,&00
    DB &B6,&61,&08,&00,&0F
    DB &83,&83,&E2,&11,&E4
    DB &21,&06,&00,&46,&31
    DB &8B,&C0,&08,&C6,&2A
    DB &20,&01,&18,&C6,&AA
    DB &00,&22,&A2,&2A,&20
    DB &04,&63,&17,&84,&00
    DB &F8,&88,&8F,&88,&84
    DB &41,&08,&22,&10,&84
    DB &21,&08,&82,&10,&44
    DB &22,&0A,&A0,&00,&00
    DB &07,&82,&D4,&B4,&3E
    DB &00,&00,&0F,&7B,&C0
    DB &F7,&BC,&00,&00,&C8
    DB &74,&7F,&07,&80

;    DB "AW,BG"

;          DS 0FFFFH-$,0


;          SEND COMPUTER1
;          END &8000     ;dummy value
