;VARS.SAM

VAR2:      EQU &5A00    ;MUST START AT PAGE BOUNDARY

;NEXT 18 BYTES INITED TOGETHER FROM 'CHIT'

LNCUR:     EQU VAR2+&00 ;CURRENT LINE CURSOR CHAR (USUALLY '>')
KURCHAR:   EQU VAR2+&01 ;(2) CURSOR CHARACTERS - LOWER CASE/UPPER CASE
BIN1DIG:   EQU VAR2+&03 ;USED BY BIN$ - USUALLY '1'
BIN0DIG:   EQU VAR2+&04 ;               USUALLY '0'
INSTHASH:  EQU VAR2+&05 ;NORMALLY '#'
PSLD:      EQU VAR2+&06 ;(2) DEVICE LETTER/NUMBER
                        ;NUMBER=TAPE SPEED/DISC NUMBER/NET STATION
SPEEDINK:  EQU VAR2+&08 ;INK FLASH COUNTER RELOAD VALUE
LINIPTR:   EQU VAR2+&09 ;(2) PTR TO LINE INTERRUPT PAL CHNG TABLE
XCMDP:     EQU VAR2+&0B ;(3) PAGE/ADDR OF FIRST EXTERNAL CMD LIST, OR FFXXXX
PRRHS:     EQU VAR2+&0E ;PRINTER RHS LIMIT - 79
AFTERCR:   EQU VAR2+&0F ;0A OR NUL ACCORDING TO WHETHER AUTO LF NEEDED
LPTPRT1:   EQU VAR2+&10 ;(2) PRINTER CONTROL PORT/01H STROBE VALUE
     ;ALL reserved for DUMP
TABVAR:    EQU VAR2+&2F ;0 IF TAB=16, ELSE TAB=8
M23LSC:    EQU VAR2+&30 ;(2) M2/3 LOWER SCREEN COLOURS
SOFE:      EQU VAR2+&32 ;FLAG FOR SCREEN OFF ENABLE/DISABLE 0=ON
TPROMPTS:  EQU VAR2+&33 ;BIT 0=1 TO SUPPRESS PRINTED NAMES DURING LOAD
                        ;BIT 1=1 TO SUPPRESS PROMPTS DURING SAVE

;START OF BLOCK SAVED WITH SWITCHED-OUT SCREEN

BGFLG:     EQU VAR2+&34 ;BLOCK GRAPHICS FLAG
FL6OR8:    EQU VAR2+&35 ;00=6 BIT CHARS IN MODE 2, NZ=8 BIT

CSIZE:     EQU VAR2+&36 ;(2) HEIGHT/WIDTH

UWRHS:     EQU VAR2+&38 ;STARTS AT 31
UWLHS:     EQU VAR2+&39 ;STARTS AT 0
UWTOP:     EQU VAR2+&3A ;STARTS AT 0
UWBOT:     EQU VAR2+&3B ;STARTS AT 18 (19 LINES IN UPPER, 2 IN LOWER SCR, 9 PIX)

;LOWER WINDOW

LWRHS:     EQU VAR2+&3C
LWLHS:     EQU VAR2+&3D
LWTOP:     EQU VAR2+&3E
LWBOT:     EQU VAR2+&3F ;STARTS AT 20

MODE:      EQU VAR2+&40
YCOORD:    EQU VAR2+&41 ;0-191, 0 AT TOP
XCOORD:    EQU VAR2+&42 ;(2) 0-255 (FAT) OR 0-511 (THIN)
RLINE:     EQU XCOORD

;PERMANENT GRAPHICS/PRINT VARS

THFATP:    EQU VAR2+&44 ;00=THIN, NZ=FAT PIXELS
ATTRP:     EQU VAR2+&45 ;ATTR USED BY MODES 0 AND 1
MASKP:     EQU VAR2+&46
PFLAGP:    EQU VAR2+&47 ;BIT 4=PAPER 9, BIT 6=INK 9
M23PAPP:   EQU VAR2+&48 ;NIBBLES OR DOUBLE BITS MATCH
M23INKP:   EQU VAR2+&49 ;00-FF. NIBBLES MUST MATCH UNLESS A DOTTED LINE WANTED.
                        ;MUST BE NEXT TO OVER FOR LD DE,(M3INKT)
OVERP:     EQU VAR2+&4A ;0-1. NORMAL OR OVER 1 (OR-ING)
INVERP:    EQU VAR2+&4B ;00/FF FOR NORMAL/INVERSE  ;
GOVERP:    EQU VAR2+&4C ;0-3. NORMAL, XOR, OR, AND ;THESE 2 LINKED
                        ;(GRAPHICS OVER - USED BY PUT)

;TEMPORARY GRAPHICS/PRINT VARS

THFATT:    EQU VAR2+&4D ;COPIED FROM THFATP WHEN MODE=2, ELSE SET TO NZ (FAT)
ATTRT:     EQU VAR2+&4E
MASKT:     EQU VAR2+&4F
PFLAGT:    EQU VAR2+&50 ;BIT 4=PAPER 9, BIT 6=INK 9
M23PAPT:   EQU VAR2+&51 ;NIBBLES OR DOUBLE BITS MATCH
M23INKT:   EQU VAR2+&52 ;00-FF. NIBBLES MUST MATCH UNLESS A DOTTED LINE WANTED
OVERT:     EQU VAR2+&53 ;0-1. NORMAL OR OVER 1 (OR-ING)
INVERT:    EQU VAR2+&54 ;00/FF FOR NORMAL/INVERSE    ;
GOVERT:    EQU VAR2+&55 ;0-3. NORMAL, XOR, OR, AND   ;LINKED

;CURRENT WINDOW (TEMP)

WINDRHS:   EQU VAR2+&56
WINDLHS:   EQU VAR2+&57
WINDTOP:   EQU VAR2+&58
WINDBOT:   EQU VAR2+&59

WINDMAX:   EQU VAR2+&5A ;(2) U. WINDOW LOWEST BOTTOM/MAX RHS
ORGOFF:    EQU VAR2+&5C ;GRAPHICS ORIGIN OFFSET
LSOFF:     EQU VAR2+&5D ;LOWER SCREEN BIT OFFSET ** THESE 3 MOVED HERE
           ;14 SPARE
SPOSNU:    EQU VAR2+&6C ;(2) SCREEN POSN (UPPER) WINDLHS, WINDTOP AFTER CLS
SPOSNL:    EQU VAR2+&6E ;(2) SCREEN POSN (LOWER) 0,19 AFTER CLS

;END OF BLOCK SAVED WITH SCREEN

PRPOSN:    EQU VAR2+&70 ;(2) PRINTER POSN (1 BYTE EXTRA FOR CONVENIENT LD)
OPCHAR:    EQU VAR2+&72 ;USED BY LPRINT - CURRENT O/P CHAR
DEVICE:    EQU VAR2+&73 ;0=US, 1=LS, 2=PRINTER, 3=
CLET:      EQU VAR2+&74 ;CURRENT CHANNEL LETTER K/S/P/B/T/$ ETC
IFTYPE:    EQU VAR2+&75 ;LONG/SHORT IF
REFFLG:    EQU VAR2+&76 ;Z IF REF VAR BEING WORKED ON
CURDISP:   EQU VAR2+&77 ;CURRENT DISPLAY
CUSCRNP:   EQU VAR2+&78 ;CURRENT SCREEN PAGE
CURP:      EQU VAR2+&79 ;CURRENT UPPER RAM PORT
CLRP:      EQU VAR2+&7A ;CURRENT LOWER RAM PORT (TEMP STORES DURING PAGING)
CSA:       EQU VAR2+&7B ;(2) CURRENT STATEMENT ADDR
FIRST:     EQU VAR2+&7D ;(2)
LAST:      EQU VAR2+&7F ;(2) LINE NUMBERS IN EG LIST X TO Y. ALSO USED BY
                        ;ARRAY SLICER

;POINTERS THAT ARE ADJUSTED BY MAKEROOM, RECLAIM:

SAVARSP:   EQU VAR2+&81
SAVARS:    EQU VAR2+&82 ;(2)     ;SAVARS/NUMEND/NVARS MUST BE IN ORDER

NUMENDP:   EQU VAR2+&84          ;NUMEND/NVARS/DATADD MUST BE IN ORDER
NUMEND:    EQU VAR2+&85 ;(2)

NVARSP:    EQU VAR2+&87
NVARS:     EQU VAR2+&88 ;(2)

DATADDP:   EQU VAR2+&8A
DATADD:    EQU VAR2+&8B ;(2)

WKENDP:    EQU VAR2+&8D
WKEND:     EQU VAR2+&8E ;(2)

WORKSPP:   EQU VAR2+&90
WORKSP:    EQU VAR2+&91 ;(2)

ELINEP:    EQU VAR2+&93
ELINE:     EQU VAR2+&94 ;(2)

CHADP:     EQU VAR2+&96
CHAD:      EQU VAR2+&97 ;(2)

KCURP:     EQU VAR2+&99
KCUR:      EQU VAR2+&9A ;(2)

NXTLINEP:  EQU VAR2+&9C
NXTLINE:   EQU VAR2+&9D  ;(2)

PROGP:     EQU VAR2+&9F
PROG:      EQU VAR2+&A0  ;(2)

XPTRP:     EQU VAR2+&A2
XPTR:      EQU VAR2+&A3  ;(2)

DESTP:     EQU VAR2+&A5
DEST:      EQU VAR2+&A6  ;(2)

PRPTRP:    EQU VAR2+&A8
PRPTR:     EQU VAR2+&A9  ;(2) PROC POINTER

;END OF ADJUSTED PTRS

DPPTRP:    EQU VAR2+&AB
DPPTR:     EQU VAR2+&AC  ;(2) DEF PROC POINTER

CLAPG:     EQU VAR2+&AE
CLA:       EQU VAR2+&AF  ;(2)

DFTFB:     EQU VAR2+&B1  ;**
STRNO:     EQU VAR2+&B2  ;CURRENT STREAM NO.
LDCO:      EQU VAR2+&B3  ;LD ZX CODE OFFSET (PAGES)
   ;       SPARE
OPSTORE:   EQU VAR2+&B5  ;(2)
DMPFG:     EQU VAR2+&B7  ;IF NZ PRINT O/P DUMPED
LISTFLG:   EQU VAR2+&B8  ;0/1/2 FOR LIST FORMAT 0/1/2
LSTFT:     EQU VAR2+&B9  ;TEMPORARY VERSION OF LISTFLG USED BY CHANNEL 'R'
INQUFG:    EQU VAR2+&BA  ;IN QUOTES FLAG. BIT 0=1 IF IN QUOTES. OUTLINE ZEROS
                         ;BIT SO INITIAL STATE IS 'OUTSIDE' AND TOKENS PRINTED
                         ;EXCEPT IN QUOTES. PRINT SETS TO 1 SO ALWAYS UDGS.
SPROMPT:   EQU VAR2+&BB  ;IF NZ NO 'SCROLL?' PROMPTS
OLDSPCS:   EQU VAR2+&BC  ;SPACE STATUS OF PREVIOUS LINE **
INDOPFG:   EQU VAR2+&BD  ;INDENTED O/P FLAG

NXTSPCS:   EQU VAR2+&BE
CURSPCS:   EQU VAR2+&BF
NXTHSPCS:  EQU VAR2+&C0
CURTHSPCS: EQU VAR2+&C1

KPOS:      EQU VAR2+&C2  ;(2) CURSOR SCREEN POSN

;NEXT 4 MUST STAY IN ORDER

SOFFCT:    EQU VAR2+&C4  ;COUNTER FOR SCREEN OFF
SOFLG:     EQU VAR2+&C5  ;FLAG FOR 'SCREEN HAS BEEN TURNED OFF' (NZ) OR ON (Z)
SPEEDIC:   EQU VAR2+&C6  ;COUNTER FOR FLASHING INKS
PALFLAG:   EQU VAR2+&C7  ;BIT 0 SHOWS WHICH PAL TABLE IN USE.

TEMPW1:    EQU VAR2+&C8  ;(2)
TEMPW2:    EQU VAR2+&CA  ;(2)
TEMPW3:    EQU VAR2+&CC  ;(2)
TEMPB1:    EQU VAR2+&CE
TEMPB2:    EQU VAR2+&CF
TEMPB3:    EQU VAR2+&D0  ;USED FOR FINAL FILL PARAM

;SYSTEM PAGE ONLY

LASTSTAT:  EQU VAR2+&D1  ;STATPORT VALUE ON LAST INTERRUPT
SPSTORE:   EQU VAR2+&D2  ;(2) SP STORE EXCLUSIVE TO INTERRUPTS

JVSP:      EQU VAR2+&D5  ;(2) JSVIN SP STORE
NMISP:     EQU VAR2+&D7  ;(2) NMI SP STORE
NMILRP:    EQU VAR2+&D9  ;(1) LRPORT VALUE WHEN NMI OCCURRED

VECTBS:    EQU VAR2+&DA  ;VECTOR BASE ADDR (0) USED BY LINK ROUTINE
DMPV:      EQU VAR2+&DA  ;(2)
SETIYV:    EQU VAR2+&DC  ;(2)
PRTOKV:    EQU VAR2+&DE  ;(2)
NMIV:      EQU VAR2+&E0  ;(2)
FRAMIV:    EQU VAR2+&E2  ;(2)
LINIV:     EQU VAR2+&E4  ;(2)
COMSV:     EQU VAR2+&E6  ;(2)
MIPV:      EQU VAR2+&E8  ;(2)
MOPV:      EQU VAR2+&EA  ;(2)
EDITV:     EQU VAR2+&EC  ;(2)
RST8V:     EQU VAR2+&EE  ;(2)
RST28V:    EQU VAR2+&F0  ;(2)
RST30V:    EQU VAR2+&F2  ;(2)
CMDV:      EQU VAR2+&F4  ;(2)
EVALUV:    EQU VAR2+&F6  ;(2)
LPRTV:     EQU VAR2+&F8  ;(2)
MTOKV:     EQU VAR2+&FA  ;(2)
MOUSV:     EQU VAR2+&FC  ;(2)
KURV:      EQU VAR2+&FE  ;(2)

CEXTAB:    EQU VAR2+&0100 ;(32) COLOUR IS APPLIED TO THIS DATA, SO EG. F0F0
                          ;MIGHT BECOME A3A3, OR IF INVERSE, 3A3A.

EXTAB:     EQU VAR2+&0120 ;(32) 16 WORDS OF MODE 3 PRINT NIBBLE->WORD DATA.
                          ;(OR 16 BYTES OF MODE 2 DOUBLED DATA)
                          ;EACH WORD (BYTE) IS THE EXPANSION OF A NIBBLE, SO
                          ;E.G. ENTRY 0A BIN 1010 =1111000011110000 OR 11001100

COMPFLG:   EQU VAR2+&0140 ;FLAG BITS USED BY LABEL/FN/PROC COMPILER
BREAKDI:   EQU VAR2+&0141 ;NZ IF BREAK BETWEEN STATEMENTS DISABLED
ERRSTAT:   EQU VAR2+&0142 ;
ERRLN:     EQU VAR2+&0143 ;(2) LINE TO GOTO ON ERROR
ONERRFLG:  EQU VAR2+&0145 ;BIT 7=TEMP ON, BIT 0=PERM ON
ONSTORE:   EQU VAR2+&0146 ;ON CMD'S STATEMENT NO.
BCSTORE:   EQU VAR2+&0147 ;(2) USED BY RST 30H
M3PAPP:    EQU VAR2+&0149 ;(2)
M3LSC:     EQU VAR2+&014B ;(2)
TEMPW4:    EQU VAR2+&014D ;(2) USED BY POINTERS
TEMPW5:    EQU VAR2+&014F ;(2) USED BY POINTERS
                          ;1 SPARE
LPT:       EQU VAR2+&0152 ;(30) 1 BYTE PRE SCREEN LINE, MARKED IF HAS A
                          ;LINE NUMBER ON IT

ANYIV:     EQU VAR2+&0170 ;ANY INTERRUPT VECTOR
RNSTKE:    EQU VAR2+&0172 ;(2) RENAME STACK PTR (PARPRO)
CURCMD:    EQU VAR2+&0174 ;CODE OF CMD BEING EXECUTED
LTDFF:     EQU VAR2+&0175 ;LET/DEFAULT FLAG
STRM16NM:  EQU VAR2+&0176 ;(11) TLBYTE/NAME OF VAR THAT STREAM 16 WRITES TO.
GRARF:     EQU VAR2+&0181 ;GRAPHICS RECORD FLAG (0=OFF)
DHADJ:     EQU VAR2+&0182 ;DOUBLE HEIGHT ADJ. 0 UNLESS BOTTOM OF DH CHAR O/PED
PAGCOUNT:  EQU VAR2+&0183 ;PAGE COUNTER USED BY FARLDIR
MODCOUNT:  EQU VAR2+&0184 ;(2) MOD 16K COUNTER USED BY FARLDIR
BCREG:     EQU VAR2+&0186 ;(2) FPC'S BC REG
AUTOFLG:   EQU VAR2+&0188
AUTOSTEP:  EQU VAR2+&0189 ;(2)
RSTEP:     EQU AUTOSTEP   ;RENUM STEP

LSPTR:     EQU VAR2+&018B ;(2) LINE SCAN PTR
LNPTR:     EQU VAR2+&018D ;(1)
MSEDP:     EQU VAR2+&018E ;(8) 018E-0195
BUTSTAT:   EQU VAR2+&018F ;MOUSE BUTTON STATUS

MXCRD:     EQU VAR2+&0196 ;(2) MOUSE X COORD
MYCRD:     EQU VAR2+&0198 ;(2) MOUSE Y COORD

;USED BY PRINTFP:

FRACLIM:   EQU VAR2+&019A ;
NPRPOS:    EQU VAR2+&019B ;(2)
DIGITS:    EQU VAR2+&019D ;   MUST
EPOWER:    EQU VAR2+&019E ;   ALL
DECPNTED:  EQU VAR2+&019F ;   STAY IN THIS ORDER!
PRNBUFF:   EQU VAR2+&01A0 ;(16) ALLOWS -0.0000123456789
                          ;     OR     -1.2345678E-35
BCDBUFF:   EQU VAR2+&01B0 ;(5)

OTHER:     EQU VAR2+&01B5 ;NET DESTINATION STATION NUMBER
DCT:       EQU VAR2+&01B6 ;DISC ERROR COUNTER

SLDEV:     EQU VAR2+&01B7 ;(2) DEVICE LETTER/NUMBER (TEMP)
                          ;NUMBER=TAPE SPEED/DISC NUMBER/NET STATION
OVERF:     EQU VAR2+&01B9 ;'SAVE OVER' FLAG. 0 IF SAVE OVER, ELSE NZ
INSLV:     EQU VAR2+&01BA ;(2)
STRLOCN:   EQU VAR2+&01BC ;(2) USED BY LOOKVARS
TVDATA:    EQU VAR2+&01BE ;(2)
DOSER:     EQU VAR2+&01C0 ;(2) JUMP AFTER DOS EXECUTION
DOSFLG:    EQU VAR2+&01C2 ;Z IF NO DOS LOADED
DOSCNT:    EQU VAR2+&01C3 ;BIT 0 IS SET IF DOS IN CONTROL
BSTKEND:   EQU VAR2+&01C4 ;(2)

;NEXT 26 BYTES INITED TOGETHER FROM MAIT

BASSTK:    EQU VAR2+&01C6 ;(2)
HEAPEND:   EQU VAR2+&01C8 ;(2)
HPST:      EQU VAR2+&01CA ;(2)
FPSBOT:    EQU VAR2+&01CC ;(2) START OF FPCS
DKDEF:     EQU VAR2+&01CE ;(2) KEY DEFS
DKLIM:     EQU VAR2+&01D0 ;(2) LIMIT OF DEF KEY BUFFER
PATOUT:    EQU VAR2+&01D2 ;(2) ADDR OF 'PRINTABLE CHARS' O/P
ERRMSGS:   EQU VAR2+&01D4 ;(2)
UMSGS:     EQU VAR2+&01D6 ;(2)
KBTAB:     EQU VAR2+&01D8 ;(2)
CMDADDRT:  EQU VAR2+&01DA ;(2) START OF CMD ADDR TABLE IN ROM0
MNOP:      EQU VAR2+&01DC ;(2) ADDR OF MAIN O/P ROUTINE
MNIP:      EQU VAR2+&01DE ;(2) ADDR OF MAIN I/P ROUTINE

PAGER:     EQU VAR2+&01E0 ;(14) RESERVED FOR PAGING S.R.

KBUFF:     EQU VAR2+&01EE ;(18) - 2 TABLES OF 72 BITS

LHM1:      EQU &5C00 ;USED BY KEYSCAN (AS 'LASTH-1')
;LASTH      EQU 5C01H ;LAST KEY HIT. 0 IF NO KEY. STOPS CHANGING IF KEYS
                     ;ARE NOT BEING READ, WHEN BUFFER FILLS. RES 5,(FLAGS)
                     ;IS SEEN AS A READ.
KDATA:     EQU &5C02
LKPB:      EQU &5C03 ;(2)
REPCT:     EQU &5C05
LASTKV:    EQU &5C06 ;(2)
LASTK:     EQU &5C08 ;KEY FROM BUFFER QUEUE HEAD. KEEPS LAST KEY VALUE.
                     ;NEEDS PERIODIC RESETS OF BIT 5,(FLAGS) OR BUFFER FILLS.
REPDEL:    EQU &5C09
REPPER:    EQU &5C0A
                     ;1 SPARE
STREAMS:   EQU &5C10 ;(42 - USES 5C0C-5C35 FOR STREAMS -5 TO 15. -4=16)
CHARS:     EQU &5C36 ;(2)
RASP:      EQU &5C38
PIP:       EQU &5C39
ERRNR:     EQU &5C3A
FLAGS:     EQU &5C3B
TVFLAG:    EQU &5C3C
ERRSP:     EQU &5C3D ;(2)
LISTSP:    EQU &5C3F ;(2)

NEWPPC:    EQU &5C42 ;(2)
NSPPC:     EQU &5C44
PPC:       EQU &5C45 ;(2)
SUBPPC:    EQU &5C47
BORDCR:    EQU &5C48 ;ATTRIBUTES FOR LOWER SCREEN IN MODES 1/2
EPPC:      EQU &5C49 ;(2)
BORDCOL:   EQU &5C4B ;VALUE TO SEND TO BORDER PORT
CHANS:     EQU &5C4F ;(2)
CURCHL:    EQU &5C51 ;(2)
DEFADDP:   EQU &5C53
DEFADD:    EQU &5C54 ;(2)
NLASTH:    EQU &5C56 ;(3)
           ;8 SPARE

ZIPLIB:    EQU &5C61 ;(2) SIMON N. GOODWIN'S
ZIPTEMP:   EQU &5C63 ;(2) COMPILER VARS
STKEND:    EQU &5C65
KPFLG:     EQU &5C67  ;FUNCTION KEYS IF EVEN, NUMBER PAD IF ODD
MEM:       EQU &5C68
FLAGS2:    EQU &5C6A
SDTOP:     EQU &5C6C
OLDPPC:    EQU &5C6E
OSPPC:     EQU &5C70
FLAGX:     EQU &5C71
STRLEN:    EQU &5C72
SEED:      EQU &5C76
FRAMES:    EQU &5C78  ;(3)
UDG:       EQU &5C7B  ;(2)
HUDG:      EQU &5C7D  ;(2)
FRAMES34:  EQU &5C7F  ;(2)
OLDPOS:    EQU &5C82
SCRCT:     EQU &5C8C

KBQB:      EQU &5C8D  ;(8) KEYBOARD QUEUE ** MOVED HERE
KBQP:      EQU &5C95  ;(2) KEYBOARD QUEUE POINTERS. LOW=END, HI=HEAD
             ;6 SPARE
SCPTR:     EQU &5C9D  ;(2) ADDR OF CURRENT SCREEN IN SCLIST

;NOT CLEARED BY NEW:

FISCRNP:   EQU &5C9F  ;PAGE OF SCREEN 1
SCLIST:    EQU &5CA0  ;(16) SCREENS LIST. MODE/PAGE OF SCREENS 1-16, OR FFH
LASTPAGE:  EQU &5CB0  ;LAST PAGE RESERVED BY BASIC
RAMTOPP:   EQU &5CB1
RAMTOP:    EQU &5CB2  ;(2)
PRAMTP:    EQU &5CB4  ;LAST PAGE PRESENT IN MACHINE

     ;SPARE

KEYWNO:    EQU &C4
TSPEED:    EQU 112

PITOK:     EQU &3B
PI:        EQU PITOK-&1A  ;SEE BELOW
INSTOK:    EQU &4A
INSTR:     EQU INSTOK-&1A ;USED TO SEPARATE N/$ IMMED CODES
FNTOK:     EQU &42 ;USED BY TPRINT
BINTOK:    EQU &43 ;USED BY TPRINT AND CALC5BY
SCRNTOK:   EQU &4C ;USED BY SAVE/LOAD
SINTOK:    EQU &53 ;USED BY TPRINT
INTOK:     EQU &60 ;
CODETOK:   EQU &6C ;USED BY SAVE/LOAD
CHRSTOK:   EQU &70 ;USED BY COPY
MODTOK:    EQU &7A ;USED BY TPRINT
ANDTOK:    EQU &80 ;USED BY TPRINT

USINGTOK:  EQU &85
ATTOK:     EQU &87
TABTOK:    EQU &88
WHILETOK:  EQU &8A
UNTILTOK:  EQU &8B
LINETOK:   EQU &8C
THENTOK:   EQU &8D
TOTOK:     EQU &8E
STEPTOK:   EQU &8F

;FORMATTOK  EQU 091H
;ERASETOK   EQU 092H
SAVETOK:   EQU &94
LOADTOK:   EQU &95
MERGETOK:  EQU &96
VERIFYTOK: EQU &97
;RECORDTOK  EQU 0EFH


BTHK:      EQU 128 ;DOS BOOT (DOS CAN IGNORE, OR INTERPRET AS ALHK)

  ;IX=HDR, IX+50H=HDL

FOPHK:     EQU 129 ;DOS OPEN (GET HEADER)
LDHK:      EQU 130 ;DOS LOAD
VFYHK:     EQU 131 ;DOS VERIFY
SVHK:      EQU 132 ;DOS SAVE

OSHK:      EQU 134 ;DOS OPEN STREAM
CSHK:      EQU 135 ;DOS CLOSE STREAM (HDR+1)=LETTER
ALHK:      EQU 136 ;DOS LOAD AUTO-LOAD FILE - FOLLOWS BOOT
DIRHK:     EQU 137


DVHK:      EQU 139 ;DOS DVAR
EOFHK:     EQU 140 ;DOS EOF
PTRHK:     EQU 141 ;DOS PTR
PATHHK:    EQU 142 ;DOS PATH$

COMM:      EQU 224 ;DISC PORTS
TRCK:      EQU 225
SECT:      EQU 226
DTRQ:      EQU 227
DRES:      EQU 9
STPIN:     EQU &59
STPOUT:    EQU &79
DRSEC:     EQU &80


;SAVE/LOAD EQUATES

HFG:       EQU 15            ;DISP TO HEADER FLAG
HDT:       EQU 26            ;DISP TO HEADER DATE/TIME
HDN:       EQU 31            ;DISP TO HEADER NUMBERS
HDRL:      EQU 80            ;HDR BUFFER LEN
NMLEN:     EQU 10            ;MAX FILE NAME LEN

YOSDISP:   EQU 57
YRGDISP:   EQU 67
XOSDISP:   EQU 77
XRGDISP:   EQU 87

RSBUFF:    EQU &E003
SBO:       EQU &8000
SBN:       EQU &C000

HPEND:     EQU &4000         ;HEAPEND

                             ;ROOM FOR DO/LOOP/PROC STACK

BSTACK:    EQU &4AFF         ;BASSTK

HDR:       EQU &4B00         ;HEADER LEN=50H. ALSO USED FOR PARPRO RENAME STK
HDL:       EQU &4B50         ;ADDRESS OF LOADED HEADER BUFFER

INTSTK:    EQU &4C00         ;USES DOWN TO 49EEH NORMALLY
BUFF256:   EQU &4C00         ;MUST BE PAGE-ALIGNED
FPSB:      EQU &4D00         ;FPSBOT
CDBUFF:    EQU &4D00         ;CODE BUFFER FOR E.G. MULTI-LDI. MAX LEN=0181H
                             ;MULTI RRD, RLD, LDD (ROLL, SCROLL, CLS)

                             ;STACK USED DOWN TO 4E98H
ISPVAL:    EQU &4F00         ;INITIAL SP VALUE

INSTBUF:   EQU &4F00         ;BUFFER FOR ROM1 XFER CODE, ETC. 0200H

MSGBUFF:   EQU INSTBUF+&01C0 ;MAX=MGT MSG

FILBUFF:   EQU &5080
ALLOCT:    EQU &5100         ;MUST START AT PAGE EDGE. 32 BYTES - 1 PER PAGE
                             ;PLUS TERMINATOR
MEMVAL:    EQU &5121
TLBYTE:    EQU &513F
NMBUFF:    EQU &5140
FIRLET:    EQU NMBUFF

NMISTK:    EQU &5188
SCRNBUF:   EQU &5188         ;8 BYTES USED BY SCREEN$ FOR COMP. FORM
CHARSVAL:  EQU &5190
PALTAB:    EQU &55D8
LINICOLS:  EQU &5600
DKBU:      EQU &5800
KTAB:      EQU &58E0

PVBUFF:    EQU &FEB0         ;IN SECOND SCREEN PAGE. HOLDS PRINT VARS OF NON-
                             ;DISPLAYED SCREEN. BGFLG-SPOSNL AT FEB0-FEEB,
                             ;CEXTAB/EXTAB AT FF7C-FFBB. FEEC-FF7B NOT USED.
                             ;FF7C-FFD7 NOT USED.
FILLSTK:   EQU PVBUFF
PALBUF:    EQU &FFD8         ;PALETTE OF NON-DISPLAYED SCREEN (ADDRESSED AT
                             ;BFD8H FOR CONVENIENCE)

SNDPORT:   EQU &FF
KEYPORT:   EQU &FE
MDIPORT:   EQU &FD
VIDPORT:   EQU &FC
URPORT:    EQU &FB
LRPORT:    EQU &FA
STATPORT:  EQU &F9
CLUTPORT:  EQU &F8

;PIADVAL    EQU 80H           ;mode 1 screen at 8000H
;ATADVAL    EQU 98H           ;mode 1 attributes
